<?php
/*completed and sumbmitted
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

// $s = "abcd"; $t = "abcde";// re 'e'
$s = "a"; $t = "aa";// re 'a'

$s_hash = [];
$t_hash = [];

for ($i=0; $i < strlen($s); $i++) 
{ 
    if(!isset($s_hash[$s[$i]])){
        $s_hash[$s[$i]] = 0;
    }
    $s_hash[$s[$i]]++;
}

for ($i=0; $i < strlen($t); $i++) 
{ 
    if((!isset($t_hash[$t[$i]])) ){
        $t_hash[$t[$i]] = 0;
    }
    $t_hash[$t[$i]]++;
}

$diff = array_diff_assoc($t_hash,$s_hash);
echo key($diff);
?>